name: CheerMeUp
version: ${project.version}
main: me.unsilencedsins.cheermeup.Core
api-version: 1.13
description: A plugin to cheer your users up.

commands:
  cheermeup:
    description: Sends a message to try to cheer up the user
    aliases: [cmu, imsad]
  cheermeupversion:
    description: Sends the current downloaded version to the sender
    aliases: [cmuv]